### ISSUE TITLE
Visual issue

### ISSUE THREAD

**Issue by gordalina** [jet8a/spotter#15]
There's a visual issue when the search box is in focus where the list is one pixel smaller than the spotter main window.

## App in focus
![](https://p2.f0.n0.cdn.getcloudapp.com/items/6quxdb6X/d5d133c6-276c-4e7e-8b36-b68efda87740.png?source=viewer&v=f3842726467477f45f020e11519798ca)

## App not in focus
![](https://p2.f0.n0.cdn.getcloudapp.com/items/WnulLmoZ/784e9dce-0a78-4a23-8427-b76ead578e82.png?source=viewer&v=5ae646c18f4a4d386fc44efc8725bec6)

**Comment by jet8a** [comment]
Hi @gordalina, thank you for the report

Can't reproduce it in [0.0.4](https://github.com/spotter-application/spotter/releases/tag/0.0.4)

<img width="660" alt="image" src="https://user-images.githubusercontent.com/14956407/105575385-9786a680-5d6b-11eb-99f6-0a14adeeda13.png">
